apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

environment:
  - NAME1: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID')[:7] }}"


metadata:
  name: ${NAME1}
  region: us-east-1

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    amiFamily: AmazonLinux2
    # desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: capkey2